### ISSUE TITLE
缺少依赖库

### ISSUE THREAD

**Issue by bc1pjerry** [Kuailun/737NG_CDU#1]
在我安装的过程中缺少两个依赖库：
PyQt5
coloredlogs

使用pip安装PyQt5
```
pip install PyQt5
```
使用pip安装coloredlogs
```
pip install coloredlogs
```

**Comment by Kuailun** [comment]
谢谢你的邮件，后面我会增加个requirement文件


这两个的确是必要的依赖库



Kind Regards,
YuChen Chai


Web:&nbsp;https://www.fycyccreativehouse.com/





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jerry Ye"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 上午10:31
收件人:&nbsp;"Kuailun/737NG_CDU"<737NG_CDU@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Kuailun/737NG_CDU] 缺少依赖库 (#1)





 
在我安装的过程中缺少两个依赖库：
 PyQt5
 coloredlogs
 
使用pip安装PyQt5
 pip install PyQt5  
使用pip安装coloredlogs
 pip install coloredlogs

**Comment by Kuailun** [comment]
问题已解决
